---
title: "title"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## exercise 1
1. Western Bulldogs won in 2018, defeating Brisbane Lions. Adelaide Crows won in 2017, defeating Brisbane Lions.
2. 2017 - Erin Phillips, 2018 - Emma Kearney

## exerciese 2
2) a) 2017 - Erin Phillips 2018 - Emma Kearney
b) players who had the most kicks had a 55-60.5% rate of dispatchment so did not necessarily kick the most
Players who had a 100% dispatchment:
2017: Natalie Plane, Kim Mickle
2018: Sarah Lampard
Players who never managed to dispatch:
2017: Taryn Priestly, Romy Timmins, Lou Wotton, Hannah Dunn 
2018: Ruby Blair, Louise Stephenson
c) 2017: The highest average goal - 2 (Darcy Vescio)
2018: Highest average goal - 1.6 ( Jess Wuetschner)
This is different from the player with the most kicks because those with the highest average number of goals did not necessarily had the most kicks where - 
Player with the most kicks: Erin Phillips in 2017, Emma Kearney in 2018

## exercise 3
1. a)
2017    36.8
2018    39.5
There was an increase of 2.7 for average goals per game going from Season 1 (2017) to Season 2 (2018).
b) See the code.

2. a) Jessica Dal Pos and Alicia Eva
    c) Yes. Dal Pos received 4 votes, while Eva received 3 votes. However, the data shows that Eva’s average number of kicks was 13.7 and average number of handballs were 4.1, while Dal Pos only had an average of 7.4 kicks and an average of 3.6 handballs. The two points are far away from each other, thus more votes should have gone to Eva, who had a greater kicking and handball average than Dal Pos.

## exercise 4
Exercise 4
1. By changing the variables, the plot changes because we have changed the relationship of the two variables we are examining. 
2. There is not much difference between the teams (they remain similar). Teams that do well often have players performing on an equal standard so there wouldn't be much of a change in performance.
3. MVP Erin Phillips 2017- neighbours: Ellie Blackburn, Katie Brennan. However, the votes for AFLW Players’ MVP, 2017 actually turned out as follows:
1. Erin Phillips (204)
2. Karen Paxman (149)
3. Darcy Vescio (132)
MVP Courtney Gum 2018 - neighbours: Kara Donellen, Jess Duffin, Karen Paxmen, Dana Hooker, Chloe Molloy, Jamie Stanton. However
AFLW Players’ MVP 2018
1. Courtney Gum, GWS Giants – 219
2. Karen Paxman, Melbourne Demons – 150 
3. Chelsea Randall, Adelaide Crows –  128

